## Config H2
spring:
  datasource:
    url: jdbc:h2:mem:digimon
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties.hibernate.format_sql: true
    generate-ddl: true
    hibernate.ddl.auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.import_files: sql/populate-database.sql